name: e_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Animations/Rive/background sky.riv
    - Assets/Images/chat app.png
    - Assets/Images/covid.png
    - Assets/Images/myself.png
    - Assets/Images/ncbae.png
    - Assets/Images/todo list.png
    - Assets/Images/vape zone.png
    - Assets/Images/weather.png
    - Assets/Icons/github.png
    - Assets/Icons/insta.png
    - Assets/Icons/linkedin.png
    - Assets/Icons/aot.png
    - Assets/Images/aumc.png
    - Assets/Images/my pic.png

  fonts:
    - family: BaskervvilleSC
      fonts:
        - asset: Assets/Fonts/BaskervvilleSC-Regular.ttf
