class TextClass {
  final String aboutMe =
      'This code is absolute 🔥!\n\nAs a determined Flutter developer, I\'ve been igniting cross-platform applications with passion and precision. My primary focus is Android development, where I\'ve honed my skills in crafting elegant UI designs that seamlessly blend with intuitive user experiences. Beyond Flutter, I\'m proficient in languages like Python, C++, and Dart, with a strong foundation in OOP principles. This versatility allows me to tackle a wide range of projects, from mobile apps to web applications. I\'m particularly adept at integrating Firebase with Flutter, leveraging its powerful backend services to build scalable and robust applications. My experience with Firebase includes real-time databases, authentication, cloud storage, and more. When I\'m not immersed in the world of coding, you\'ll find me exploring my passion for cars. I\'m a car enthusiast who enjoys staying up-to-date with the latest trends and technologies in the automotive industry. Additionally, I\'m an avid traveler, always eager to discover new cultures and experiences. My ability to combine technical expertise with a creative mindset allows me to deliver exceptional results. I\'m committed to staying at the forefront of technological advancements and continuously expanding my skill-set. I\'m confident that my skills and experience make me a valuable asset to any team. Futhermore I am a Student at Air University Multan Campus and pursuing my degree in Bachelors of Computer Science.';

  final String covid =
      "The Covid-19 Tracker Application, a sophisticated API-driven project, offers a comprehensive and up-to-date overview of the global pandemic, providing users with a wealth of information and insights. Its intuitive interface and visually appealing design make it a user-friendly tool that empowers individuals to explore current statistics for affected countries, track the spread of the virus, and access detailed information about individual nations. From global overviews showcasing the pandemic's worldwide impact to country-specific breakdowns offering insights into total cases, tests conducted, recovered patients, tragic losses, and active and critical cases, the Covid-19 Tracker is an invaluable resource for staying informed and making informed decisions. Whether you're a healthcare professional, a concerned citizen, or simply curious about the pandemic's evolution, this application provides a wealth of information at your fingertips. Its user-friendly features, coupled with its real-time data updates, make it a must-have for anyone seeking to understand and navigate the complexities of the Covid-19 pandemic. Additionally, the Covid-19 Tracker Application offers a range of features designed to enhance the user experience: \n\n* Real-time data updates: Stay informed with the latest statistics and trends as they unfold.\n* Interactive maps: Visualize the spread of the virus across the globe.\n* Customizable alerts: Receive notifications based on your preferences and interests.\n* Comparative analysis: Compare data across different countries and regions.\n* Educational resources: Access informative articles and videos about Covid-19.\nWith its comprehensive features and user-friendly design, the Covid-19 Tracker Application is a powerful tool for understanding and navigating the complexities of the pandemic.";

  final String projects =
      "Explore a curated collection of personal projects that showcase my diverse skill set, ranging from front-end development to back-end engineering and management. Each project is a testament to my passion for crafting innovative solutions. To gain a deeper understanding of my approach and technical prowess, I invite you to explore the source code for these projects on GitHub. Feel free to inspect, analyze, and even contribute to my work.";

  final String education =
      "I am  a student of Air University. I am currently Studying Bachelors in Computer Science. The university has enabled me to understand different complex algorithms used in this field. My hard-work dedication and the efforts of my beloved teachers has enabled me to create an elegant design in coding universe. Not only my concepts related to different niche are clear also I have a motivation for building Attractive User interfaces with strong backend technologies. I hope to enhance it further more!";

  final String android =
      'I have developed multiple android applications in flutter with some elegant user Interfaces and smooth and functional back-ends. My primary expertise are in Android development all the projects are available on my GitHub and also displayed on LinkedIn.';
  final String ios =
      'I have developed multiple ios applications in flutter with some elegant user Interfaces and smooth and functional back-ends. I am a Cross Platform Developer and all the projects are available on my GitHub and also displayed on LinkedIn.';
  final String web =
      'I have developed some web applications in flutter with some elegant user Interfaces and smooth and functional back-ends like this portfolio. I am a Cross Platform Developer and all the projects are available on my GitHub and also displayed on LinkedIn.';
  final String desktop =
      'I have developed some desktop applications in flutter with some elegant user Interfaces and smooth and functional back-ends. I am a Cross Platform Developer and all the projects are available on my GitHub and also displayed on LinkedIn.';
}
